name: 'Update EAS Dynamic Config Build Numbers'
description:
  'An action to update buildNumber and versionCode when using a dynamic app
  config file'
author: 'Jordan Riser'

# Define your inputs here.
inputs:
  configPath:
    description: 'The location of your app config file'
    required: false
    default: './app-config.js'
  updateIos:
    description: 'Weather or not to run the update for iOS buildNumber'
    required: false
    default: true
  updateAndroid:
    description: 'Weather or not to run the update for android versionCode'
    required: false
    default: true

outputs:
  newIosBuildNumber:
    description:
      'The build number that was updated if updateIos was set to true'
  newAndroidVersionCode:
    description:
      'The version code that was updated if updateAndroid was set to true'

runs:
  using: node20
  main: dist/index.js
